project:
  type: book
  output-dir: _book

book:
  title: "GIS for Urban Planning: QGIS methods"
  author: "Dr. Kam Tin Seong"
  date: "08/11/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - Hands-on_Ex01.qmd
    - Hands-on_Ex02.qmd
    - Hands-on_Ex03.qmd
    - Hands-on_Ex04.qmd
    - Hands-on_Ex05.qmd
    - Hands-on_Ex06.qmd
    - Hands-on_Ex07.qmd
    - Hands-on_Ex08.qmd
    - Hands-on_Ex09.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

